import { Market } from './market.interface';

export const MARKET: Market[] = [
{
    id : 1,
    name : 'Blabla',
    object: 'A propos de',
    caseNbr: 12,
    marketNbr: 24,
    Procedure: 'Appel d\'offre ouvert',
    state: 'En réflexion',
    comment: 'Good',
    FDB: '',
    QS: '',
    CDCF: '',
    launchMeetDate: 'Date du jour',
    securityForm: '',
    securityAnnexe: '',
    framMeetingDate: 'Demain',
    lauchConsultDate: 'Demain',
    RAOdate: 'Date du jour',
    holder: 1,
    notificationDate: '',
    startDateExe: 'Hier',
    duration: 'longtemps',
    CalculEndDate: 'Demain',
    minAmount: 10,
    maxAmount: 1000,
    calculMaxAmount: '900',
    CCTP: '',
    CCAP: '',
    CCAG: '',
    CCP: '',
    AE: '',
    LDP: '',
    annexPrice: ''
},
{
    id : 2,
    name : 'Et avec ceci',
    object: 'A propos de',
    caseNbr: 12,
    marketNbr: 24,
    Procedure: 'Appel d\'offre ouvert',
    state: 'En réflexion',
    comment: 'Good',
    FDB: '',
    QS: '',
    CDCF: '',
    launchMeetDate: 'Date du jour',
    securityForm: '',
    securityAnnexe: '',
    framMeetingDate: 'Demain',
    lauchConsultDate: 'Demain',
    RAOdate: 'Date du jour',
    holder: 1,
    notificationDate: '',
    startDateExe: 'Hier',
    duration: 'longtemps',
    CalculEndDate: 'Demain',
    minAmount: 10,
    maxAmount: 1000,
    calculMaxAmount: '900',
    CCTP: '',
    CCAP: '',
    CCAG: '',
    CCP: '',
    AE: '',
    LDP: '',
    annexPrice: ''
}
];

